### PR TITLE
Fix describe_log_streams error

### LINKED ISSUE #48: MethodError: no method matching describe_log_streams
I encountered this crash:

```julia
Unhandled Task ERROR: MethodError: no method matching describe_log_streams(::String, ::Dict{String, Any}; aws_config=AWSConfig((<redacted>, <redacted>, <redacted>), "us-east-2", "json", 3))
Stacktrace:
  [1] describe_log_streams(config::AWSConfig, log_group_name::String, params::Dict{String, Any})
    @ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:137
  [2] macro expansion
    @ ~/.julia/packages/Mocking/HMh91/src/mock.jl:26 [inlined]
  [3] (::CloudWatchLogs.var"#12#15"{AWSConfig, String, String})()
    @ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:153
  [4] (::Base.var"#88#90"{Base.var"#88#89#91"{ExponentialBackOff, typeof(CloudWatchLogs.aws_retry_cond), CloudWatchLogs.var"#12#15"{AWSConfig, String, String}}})(; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./error.jl:296
  [5] #88
    @ ./error.jl:291 [inlined]
  [6] aws_retry
    @ ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:15 [inlined]
  [7] new_sequence_token(config::AWSConfig, log_group::String, log_stream::String)
    @ CloudWatchLogs ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:152
  [8] new_sequence_token
    @ ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:131 [inlined]
  [9] update_sequence_token!
    @ ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:195 [inlined]
 [10] CloudWatchLogStream
    @ ~/.julia/packages/CloudWatchLogs/eMIGi/src/stream.jl:38 [inlined]
```

It looks to be caused by this commit https://github.com/JuliaCloud/AWS.jl/commit/b8086407368c27dc21500f5a55f66a267b7d2619
Take a look at the prior state of this line https://github.com/JuliaCloud/AWS.jl/blame/7b09ec01ab2a06471ce7a0101535c60472659634/src/services/cloudwatch_logs.jl#L775

Current: `function describe_log_streams(; aws_config::AbstractAWSConfig=global_aws_config())`
Previous: `function describe_log_streams(
    logGroupName; aws_config::AbstractAWSConfig=global_aws_config()
)`

CloudWatchLogs.jl version v2.1.0
AWS.jl version v1.84.1
Julia v1.8.5

### PR DESCRIPTION
**Pull request by iamed2**
Commits from @octogonapus https://github.com/invenia/CloudWatchLogs.jl/pull/49 on a new branch to make CI work

Fixes #48

### CODE REVIEW

File: src/stream.jl [hunk 1]
```diff
@@ -134,7 +134,9 @@ end
 function describe_log_streams(
     config::AWSConfig, log_group_name::AbstractString, params::AbstractDict
 )
-    return CloudWatch_Logs.describe_log_streams(log_group_name, params; aws_config=config)
+    full_params = Dict("logGroupName" => log_group_name)
+    append!(full_params, params)
```
Comment (iamed2) [inline src/stream.jl:138]:
```suggestion
    full_params = Dict{String,Any}("logGroupName" => log_group_name)
    merge!(full_params, params)
```
Params passed in are not necessarily strings, so the new dict is given `Any` element type. `merge!` is like `append!` but for dicts.

**Comment by iamed2** [comment]
I think https://github.com/invenia/CloudWatchLogs.jl/pull/51 removing 1.3 will make this mergeable (although version number will need to change too).

**Review by mattBrzezinski — APPROVED** [review]
bors r+
